export enum CallStatus {
  CONNECTED = 'CONNECTED',
  NOT_REACHABLE = 'NOT_REACHABLE',
  INTERESTED = 'INTERESTED',
  REJECTED = 'REJECTED',
  CALLBACK_REQUESTED = 'CALLBACK_REQUESTED',
  DONATED = 'DONATED',
}
