"""add_post_tags_moods_v3

Revision ID: d7c0f3dca8bb
Revises: fea2447f1bd1
Create Date: 2026-07-14 18:17:44.334556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7c0f3dca8bb'
down_revision: Union[str, None] = 'fea2447f1bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_moods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_moods_mood'), 'post_moods', ['mood'], unique=False)
    op.create_index(op.f('ix_post_moods_post_id'), 'post_moods', ['post_id'], unique=False)
    op.create_table('post_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_tags_post_id'), 'post_tags', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_tags_tag'), 'post_tags', ['tag'], unique=False)
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('ANXIETY', 'DEPRESSION', 'STRESS', 'WORK', 'RELATIONSHIPS', 'GRIEF', 'GENERAL', name='post_category_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category',
               existing_type=sa.Enum('ANXIETY', 'DEPRESSION', 'STRESS', 'WORK', 'RELATIONSHIPS', 'GRIEF', 'GENERAL', name='post_category_enum', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.drop_index(op.f('ix_post_tags_tag'), table_name='post_tags')
    op.drop_index(op.f('ix_post_tags_post_id'), table_name='post_tags')
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_post_moods_post_id'), table_name='post_moods')
    op.drop_index(op.f('ix_post_moods_mood'), table_name='post_moods')
    op.drop_table('post_moods')
    # ### end Alembic commands ###
