"""add anonymous users and new models

Revision ID: eabaa637eb84
Revises: 0009
Create Date: 2026-06-19 21:53:53.248369

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app
from alembic import op

revision: str = 'eabaa637eb84'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_completions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('meditation', sa.Boolean(), nullable=False),
    sa.Column('meditation_duration', sa.Integer(), nullable=True),
    sa.Column('task', sa.Boolean(), nullable=False),
    sa.Column('reflection', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', 'completion_date', name='uq_user_day_date')
    )
    op.create_index(op.f('ix_daily_completions_user_id'), 'daily_completions', ['user_id'], unique=False)
    op.create_table('emotion_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('primary_emotions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('secondary_emotions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('themes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('possible_core_issue', sa.String(), nullable=False),
    sa.Column('intensity', app.db_types.PgEnum(app.models.emotion_analysis.IntensityLevel), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_analyses_created_at'), 'emotion_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_emotion_analyses_user_id'), 'emotion_analyses', ['user_id'], unique=False)
    op.create_table('meditation_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meditation_sessions_user_id'), 'meditation_sessions', ['user_id'], unique=False)
    op.create_table('psychologist_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('recommendations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('risk_level', app.db_types.PgEnum(app.models.psychologist_summary.RiskLevel), nullable=False),
    sa.Column('analysis_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychologist_summaries_generated_at'), 'psychologist_summaries', ['generated_at'], unique=False)
    op.create_index(op.f('ix_psychologist_summaries_user_id'), 'psychologist_summaries', ['user_id'], unique=False)
    op.create_table('test_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('metadata_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_scores_created_at'), 'test_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_scores_test_id'), 'test_scores', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_scores_user_id'), 'test_scores', ['user_id'], unique=False)
    op.drop_index('ix_departments_org_id', table_name='departments')
    op.create_unique_constraint(None, 'invitations', ['token_hash'])
    op.drop_index('ix_mood_logs_user_logged_at', table_name='mood_logs')
    op.create_index('ix_mood_logs_user_logged_at', 'mood_logs', ['user_id', 'logged_at'], unique=False)
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.add_column('users', sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'email_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_users_department_id', table_name='users')
    op.drop_index('ix_users_manager_id', table_name='users')
    op.drop_index('ix_users_org_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_org_id', 'users', ['org_id'], unique=False)
    op.create_index('ix_users_manager_id', 'users', ['manager_id'], unique=False)
    op.create_index('ix_users_department_id', 'users', ['department_id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('users', 'is_anonymous')
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.drop_index('ix_mood_logs_user_logged_at', table_name='mood_logs')
    op.create_index('ix_mood_logs_user_logged_at', 'mood_logs', ['user_id', sa.text('logged_at DESC')], unique=False)
    op.drop_constraint(None, 'invitations', type_='unique')
    op.create_index('ix_departments_org_id', 'departments', ['org_id'], unique=False)
    op.drop_index(op.f('ix_test_scores_user_id'), table_name='test_scores')
    op.drop_index(op.f('ix_test_scores_test_id'), table_name='test_scores')
    op.drop_index(op.f('ix_test_scores_created_at'), table_name='test_scores')
    op.drop_table('test_scores')
    op.drop_index(op.f('ix_psychologist_summaries_user_id'), table_name='psychologist_summaries')
    op.drop_index(op.f('ix_psychologist_summaries_generated_at'), table_name='psychologist_summaries')
    op.drop_table('psychologist_summaries')
    op.drop_index(op.f('ix_meditation_sessions_user_id'), table_name='meditation_sessions')
    op.drop_table('meditation_sessions')
    op.drop_index(op.f('ix_emotion_analyses_user_id'), table_name='emotion_analyses')
    op.drop_index(op.f('ix_emotion_analyses_created_at'), table_name='emotion_analyses')
    op.drop_table('emotion_analyses')
    op.drop_index(op.f('ix_daily_completions_user_id'), table_name='daily_completions')
    op.drop_table('daily_completions')
    # ### end Alembic commands ###
