"""make org_id not null

Revision ID: fdb6aab16281
Revises: 65df3fda0579
Create Date: 2026-06-19 22:36:00.087150

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'fdb6aab16281'
down_revision: str | None = '65df3fda0579'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
