"""replace_meditation_session_with_mindful_architecture

Revision ID: fea2447f1bd1
Revises: 05da859c0793
Create Date: 2026-07-14 10:47:22.842811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fea2447f1bd1'
down_revision: Union[str, None] = '05da859c0793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meditation_tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('GUIDED', 'SLEEP', 'RELAXATION', 'FOCUS', 'STRESS', 'ANXIETY', name='meditation_category_enum', native_enum=False), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='meditation_difficulty_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meditation_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['meditation_tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meditation_history_track_id'), 'meditation_history', ['track_id'], unique=False)
    op.create_index(op.f('ix_meditation_history_user_id'), 'meditation_history', ['user_id'], unique=False)
    op.create_table('meditation_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_meditated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index('ix_meditation_sessions_user_id', table_name='meditation_sessions')
    op.drop_table('meditation_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meditation_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='meditation_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='meditation_sessions_pkey')
    )
    op.create_index('ix_meditation_sessions_user_id', 'meditation_sessions', ['user_id'], unique=False)
    op.drop_table('meditation_stats')
    op.drop_index(op.f('ix_meditation_history_user_id'), table_name='meditation_history')
    op.drop_index(op.f('ix_meditation_history_track_id'), table_name='meditation_history')
    op.drop_table('meditation_history')
    op.drop_table('meditation_tracks')
    # ### end Alembic commands ###
